### ISSUE TITLE
Friend Pages Not Scraped

### ISSUE THREAD

**Issue by getshaun24** [rugantio/fbcrawl#15]
Hi

Thank you for your contribution, this repo is awesome!

When scraping a persons 'page' like a celebrity or public figure the program works perfectly without a hitch. 
The problem arises when scraping a friends profile, scraping stops after only 1 page. 
Also, when trying to scrape the limited 'profile' available of someone whom I am not friends with, nothing is scraped.

I am willing to fix this issue myself and contribute where I can, however, I mostly do ml and have little knowledge of web. 
If someone can help resolve this (saving me much precious time) or guide me, that would highly be appreciated. 

Thank You!

**Comment by rugantio** [comment]
Hi, I'm glad you're enjoying the tool! This issue has been addressed already, check out #13
