### ISSUE TITLE
Hi guys how to extract group member data?by scrapy

### ISSUE THREAD

**Issue by ademjemaa** [rugantio/fbcrawl#31]
Hi guys how to extract group member data?by scrapy

_Originally posted by @maaudrana in https://github.com/rugantio/fbcrawl/issues/20#issuecomment-491150184_

**Comment by rugantio** [comment]
I added support for crawling groups, just pass the group link using the page parameter `-a page`. It should be working both for the fb and the comments crawler. This feature is still experimental and needs testing, please report any issues.
