### ISSUE TITLE
Crawl posts image as well?

### ISSUE THREAD

**Issue by theblackcat102** [rugantio/fbcrawl#41]
Is it possible to include image as well?
I assume it will be added at fbcrawl.py parse_post function, however I am not sure about the html hierarchy path and the format should be stored as csv. If someone can pointed the possible path I can write the required code and submit a PR for this.

**Comment by mnba** [comment]
what did you mean by "html hierarchy path", can't you get it using WebDeveloper tools? like press F12, click on "Inspect" highlight the facebook post image, take the image URL from there ?... clean it up and insert into the code

**Comment by theblackcat102** [comment]
@mnba  If you are crawling for one image sure this approach may work. But I would like to crawl the complete images (full resolutions ones). Since this is a public repo, I also want to hear how does the author wish to handle list of string within CSV columns (maybe separated using tabs within img columns?)

**Comment by ademjemaa** [comment]
you can use the built in scrapy image extraction functions. 

https://docs.scrapy.org/en/latest/topics/media-pipeline.html

**Comment by theblackcat102** [comment]
I have completed the function in my branch, Thanks everyone

**Comment by hkbk** [comment]
how cralwer image from facebook fanpage?
Can you hlep me? @theblackcat102

**Comment by theblackcat102** [comment]
@hkbk  Sorry for the late reply, you can checkout my fork version of fbcrawl at this [line](https://github.com/theblackcat102/fbcrawl/blob/master/fbcrawl/pipelines.py#L43). Basically an iterative sequence to find all the post image ( if exists ). Or you can try my fbcrawl with the postgresql part commented out on a fanpage link and see if it works?

**Comment by hkbk** [comment]
> @hkbk Sorry for the late reply, you can checkout my fork version of fbcrawl at this [line](https://github.com/theblackcat102/fbcrawl/blob/master/fbcrawl/pipelines.py#L43). Basically an iterative sequence to find all the post image ( if exists ). Or you can try my fbcrawl with the postgresql part commented out on a fanpage link and see if it works?

- @theblackcat102  : basically crawler public and private facebook's group but we checkpoint from Facebook. Can you for an idea to pass checkpoint? thanks.

**Comment by theblackcat102** [comment]
@hkbk can you explain what does checkpoint from Facebook means?
