### ISSUE TITLE
Could I create a pull request?

### ISSUE THREAD

**Issue by laols574** [rugantio/fbcrawl#51]
Hello, 

I'm just proposing a pull request. I've adding error handling for getting blocked and using incorrect and old passwords. I've created capability for viewing more complex reaction data and profile data within comments.py so you can view a single csv file with all of this information. I added some random time pauses to avoid blocking and extend the amount of data collected from profiles. I also noticed that the comment parser only would recurse backwards through comments even though sometimes on mbasic comment threads (especially long ones) would start in the middle of a comment thread, losing out on lots of data. I'd like to create a pull request and have you look over my code if possible. Also, thank you so much for creating your code, it wa s incredibly helpful for my research into social media data.

**Comment by rugantio** [comment]
Hi,
thx for your interest & appreciation! please do make the PR, I intend to get back to the project as new year arrives. I will be glad to review & integrate the changes!
