### ISSUE TITLE
Empty page comments file

### ISSUE THREAD

**Issue by Rahulsunny11** [rugantio/fbcrawl#65]
Hi, @rugantio  
I ran following command to scrape all comments in  Trump page but the output csv file is empty
`scrapy crawl comments -a email="" -a password="" -a page="DonaldTrump" -a date="2020-04-04" -a lang="it" -o trumpcomments.csv`

**Comment by lijia-ma** [comment]
I got the same problem.

**Comment by Rahulsunny11** [comment]
just change line44 to `for post in response.xpath("//article[contains(@data-ft,'top_level_post_id')]"):` it will work
