### ISSUE TITLE
No module named "items" 

### ISSUE THREAD

**Issue by n41al** [rugantio/fbcrawl#7]
Hello,

Im getting a problem while running the command. 
It sames that there is no module to import named items. I don´t know if its about a library a dont have installed or its an other setting i didn´t configure.

pls find the screenshot related to the error.

![imagen](https://user-images.githubusercontent.com/46488247/50972476-04150c80-14e7-11e9-81e3-52b6b226d565.png)

Thanks for your help.

**Comment by ortenburger** [comment]
No, it's not a Lib -- items.py is in the folder. My guess is that you didn't set up/run fbcrawl properly.

**Comment by n41al** [comment]
I have run with this sentence "scrapy crawl fb -a email="___" -a password="___" -a page="____" -o DUMPFILE.csv" Is something wrong in it?

Thanks for yout help

**Comment by n41al** [comment]
I would like to know which are the libraries I have to install. "Requirements are: python3 (python2 is also supported), scrapy and other dependencies libraries **(twisted, libxml2 etc.)**."

Thanks.

**Comment by n41al** [comment]
Please, Can anybody help me?

**Comment by rugantio** [comment]
Probably your issue is related to the fact that you're using python 2.7, try with python3 and let me know how it goes

**Comment by n41al** [comment]
It works with python3, but I have had another code error. 
 File "/usr/local/lib/python3.6/dist-packages/OpenSSL/SSL.py", line 309, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: module 'lib' has no attribute 'X509_up_ref'

I try to solved it, but I can't. 

thanks

**Comment by rugantio** [comment]
you need to pull pyOpenSSL from pip

**Comment by n41al** [comment]
Now works!

Thanks!
